# Generated by Django 4.1.2 on 2022-11-03 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_osoba_options_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Osoba',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['nazwisko']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Adam', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='miesiac_urodzenia',
            field=models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='nazwisko',
            field=models.CharField(default='Kowalski', max_length=20),
            preserve_default=False,
        ),
    ]
