# Generated by Django 4.1.2 on 2022-11-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
    ]
