# Generated by Django 4.1.2 on 2022-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='PL', max_length=2),
            preserve_default=False,
        ),
    ]
