# Generated by Django 4.1.2 on 2022-11-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
    ]
