# Generated by Django 4.1.3 on 2022-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_person_miesiac_urodzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='miesiac_urodzenia',
        ),
        migrations.AddField(
            model_name='person',
            name='miesiac_dodania',
            field=models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=4),
        ),
    ]
